trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: Default

stages:

#========================================================
# PRE-COMMIT STAGE
#========================================================
- stage: PreCommit
  displayName: "Pre-Commit / Static Analysis"

  jobs:

  - job: TerraformValidate
    displayName: "Terraform Validate"

    steps:

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev
        backendServiceArm: ericsson
        backendAzureRmResourceGroupName: sohit-rg
        backendAzureRmStorageAccountName: sohittfstate001
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: sohit.terraform.tfstate
        commandOptions: -upgrade

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev

#========================================================

  - job: TerraformFmt
    dependsOn: TerraformValidate
    displayName: "Terraform Format"

    steps:

    - task: PowerShell@2
      displayName: Terraform fmt
      inputs:
        targetType: inline
        script: |
          Set-Location "$(Build.SourcesDirectory)\env\dev"
          terraform fmt -recursive -check

#========================================================

  - job: Gitleaks
    dependsOn: TerraformFmt

    steps:

    - task: PowerShell@2
      displayName: Gitleaks Scan
      continueOnError: true
      inputs:
        targetType: inline
        script: |
          Set-Location "$(Build.SourcesDirectory)\env\dev"

          gitleaks detect `
          --source . `
          --report-format json `
          --report-path "$(Build.ArtifactStagingDirectory)\gitleaks-report.json"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)\gitleaks-report.json"
        ArtifactName: gitleaks-report

#========================================================

  - job: TFLint
    dependsOn: Gitleaks

    steps:

    - task: PowerShell@2
      displayName: TFLint
      continueOnError: true
      inputs:
        targetType: inline
        script: |
          Set-Location "$(Build.SourcesDirectory)\env\dev"

          tflint --init
          tflint --recursive --format compact > "$(Build.ArtifactStagingDirectory)\tflint.txt"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)\tflint.txt"
        ArtifactName: tflint-report

#========================================================

  - job: TFSEC
    dependsOn: TFLint

    steps:

    - task: PowerShell@2
      displayName: tfsec
      continueOnError: true
      inputs:
        targetType: inline
        script: |
          Set-Location "$(Build.SourcesDirectory)\env\dev"

          tfsec . `
          --format json `
          --out "$(Build.ArtifactStagingDirectory)\tfsec-report.json"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)\tfsec-report.json"
        ArtifactName: tfsec-report

#========================================================
# INFRACOST
#========================================================

- stage: InfraCost
  dependsOn: PreCommit

  jobs:

  - job: Infracost

    steps:

    - task: PowerShell@2
      displayName: Infracost
      inputs:
        targetType: inline
        script: |
          Set-Location "$(Build.SourcesDirectory)\env\dev"

          infracost breakdown `
          --path . `
          --format json `
          --out-file "$(Build.ArtifactStagingDirectory)\infracost.json"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)\infracost.json"
        ArtifactName: infracost

#========================================================
# PLAN
#========================================================

- stage: Plan
  dependsOn: InfraCost

  jobs:

  - job: TerraformPlan

    steps:

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev
        backendServiceArm: ericsson
        backendAzureRmResourceGroupName: sohit-rg
        backendAzureRmStorageAccountName: sohittfstate001
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: sohit.terraform.tfstate
        commandOptions: -upgrade

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev
        environmentServiceNameAzureRM: ericsson
        commandOptions: "-out=tfplan"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.SourcesDirectory)\env\dev\tfplan"
        ArtifactName: tfplan

#========================================================
# APPROVAL
#========================================================

- stage: Approval
  dependsOn: Plan

  jobs:

  - job: ManualApproval

    pool: server

    steps:

    - task: ManualValidation@1
      inputs:
        notifyUsers: |
          sohitg89@gmail.com
        approvers: |
          sohitg89@gmail.com

#========================================================
# APPLY
#========================================================

- stage: Apply
  dependsOn: Approval

  condition: and(succeeded(), eq(variables['Build.SourceBranch'],'refs/heads/main'))

  jobs:

  - job: TerraformApply

    steps:

    - task: DownloadBuildArtifacts@1
      inputs:
        artifactName: tfplan
        downloadPath: "$(Pipeline.Workspace)"

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev
        backendServiceArm: ericsson
        backendAzureRmResourceGroupName: sohit-rg
        backendAzureRmStorageAccountName: sohittfstate001
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: sohit.terraform.tfstate

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev
        environmentServiceNameAzureRM: ericsson
        commandOptions: "$(Pipeline.Workspace)\tfplan\tfplan"